from ..states import REGISTER_CONTENT_CREATOR

FIRST_NAME = REGISTER_CONTENT_CREATOR + '0'
COUNTRY = REGISTER_CONTENT_CREATOR + '1'
AGE = REGISTER_CONTENT_CREATOR + '2'
BIO = REGISTER_CONTENT_CREATOR + '3'
PROFILE_PIC = REGISTER_CONTENT_CREATOR + '4'
