from ..states import REGISTER_CONTENT_CREATOR

FIRST_NAME = REGISTER_CONTENT_CREATOR + '0'
LAST_NAME = REGISTER_CONTENT_CREATOR + '1'
EMAIL = REGISTER_CONTENT_CREATOR + '2'
BIRTH_DATE = REGISTER_CONTENT_CREATOR + '3'
COUNTRY = REGISTER_CONTENT_CREATOR + '4'
